# Generated by Django 4.2.3 on 2023-08-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoWorkModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=200)),
                ('status', models.CharField(choices=[('in complete', 'in complete'), (' complete', ' complete')], max_length=30)),
            ],
        ),
    ]
