# Generated by Django 4.2.3 on 2023-08-14 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoworkmodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
